#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.4.3f1_8a9509a5aff9"
#define UNITY_VERSION_FULL_NICE "2018.4.3f1 (8a9509a5aff9)"
#define UNITY_VERSION_BLD 9082121
#define UNITY_VERSION_DATE 1561332316
#define UNITY_VERSION_WIN "2018.4.3.9082121"
#define UNITY_VERSION_BRANCH "2018.4/staging"
